version: 2
jobs:
  build:
    docker: 
      - image: srcml/ubuntu_x86_64_base
    steps:
      - checkout
      - run: cd src && make VideoStore.o
      - run: mkdir -p bin && mv src/VideoStore.o bin/
      - run: mkdir -p obj && cp bin/VideoStore.o obj/
      - persist_to_workspace:
          root: bin
          paths:
            - VideoStore.o
      - persist_to_workspace:
          root: obj
          paths:
            - VideoStore.o

  test:
    docker: 
      - image: srcml/ubuntu_x86_64_base
    steps:
      - checkout
      - attach_workspace:
          at: bin
      - attach_workspace:
          at: obj
      - run: cp bin/VideoStore.o src/
      - run: cd src && make all

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build