version: 2
jobs:
  build:
    docker: 
      - image: srcml/ubuntu_x86_64_base
    steps:
      - checkout
      - run: cd src && make run

  test:
    docker: 
      - image: srcml/ubuntu_x86_64_base
    steps:
      - checkout
      - run: cd src && make all

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build